name: Deploy To Google Play

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

      - name: Post Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  distribute:
    name: Distribute release bundle to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Handle Version Code/Name
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle
          version: ${{ github.run_number + 3 }}

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release Bulde
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.MARTP_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyPassword: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.GOOGLE_PLAY_AUTH_JSON }}' > service_account.json

      - name: Deply Bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: manoellribeiro.dev.martp
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: 'completed'
          whatsNewDirectory: distribution
